# Generated by Django 5.2.5 on 2025-08-24 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_user_profile_user_alter_profile_date_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='name',
        ),
    ]
