# Generated by Django 5.2.5 on 2025-09-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_invoice_order_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
